# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'


services:
  streamwave:
    build: /WebApi
    ports:
      - "5077:5077"
    depends_on: 
      - mssql
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=StreamWave;User Id=sa;Password=Password123!;Encrypt=False


  nginx:
      restart: always
      image: nginx:1-alpine
      ports:
        - 8089:80
      depends_on:
        - streamwave
      volumes:
        - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx/data/www:/var/www
    
    
  mssqldata:
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
      - mssql-data:/var/opt/mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    networks:
      - app-network
    volumes:
      - ./scripts:/usr/src/app
    working_dir: /usr/src/app
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Password123!
    depends_on:
      - mssqldata
volumes:
  mssql-data:


networks:
  app-network:
    driver: bridge